Google auth
green-fox-academy/megalotis-emerald pull request #1
Opened 2019-04-18 13:45 UTC by fabianzs

2019-04-18 14:26 UTC, JohnLackland submitted a review, later dismissed
It seems good to me.

2019-04-22 18:33 UTC, szirmi requested changes

2019-04-22 18:33 UTC, szirmi commented on ASP.NET-Core-Webapp/Services/AuthService.cs
> +            //var securetoken = tokenHandler.WriteToken(token);
please always remove unnecessary code

2019-04-22 18:33 UTC, szirmi commented on ASP.NET-Core-Webapp/Services/AuthService.cs
> +            string redirect_uri = "http://localhost:5001/auth";
move this in development configuration
(in this case we need to change code to be able to deploy)

2019-04-22 18:33 UTC, szirmi commented on ASP.NET-Core-Webapp/Services/AuthService.cs
> +            dict.Add(new KeyValuePair<string, string>("redirect_uri", "http://localhost:5001/auth"));
instead of (redundant) string argument use the variable above

2019-04-24 08:23 UTC, szirmi approved these changes

2019-04-24 08:25 UTC, merged