Mock post badges endpoint
green-fox-academy/megalotis-emerald pull request #2
Opened 2019-04-18 13:46 UTC by molnarln

Boti, please review my request!
Thx in advance!

2019-04-18 14:39 UTC, Balogh08 submitted a review, later dismissed
+196,000 lines seem to be fine to me.

2019-04-22 18:40 UTC, szirmi requested changes
please remove **UnitTestProject1** because it's not part of the application
even packages folder, it shouldn't be in git

2019-04-22 18:40 UTC, szirmi commented on ASP.NET-Core-Webapp/Controllers/BadgeController.cs
> +            //    return StatusCode(401, new { error = "Unauthorized" });
please always remove unnecessary code

2019-04-22 18:40 UTC, szirmi commented on ASP.NET-Core-Webapp/Entities/LevelEntity.cs
> +    public class LevelEntity
be consistent about naming!
if one entity is **Badge**, then this entity should be **Level** (or vice versa)

2019-04-23 09:59 UTC, szirmi approved these changes

2019-04-23 10:00 UTC, merged