Mock #get badges endpoint
green-fox-academy/megalotis-emerald pull request #3
Opened 2019-04-18 14:32 UTC by JohnLackland

Review my endpoint, please!

2019-04-18 14:48 UTC, molnarln reviewed
Added 1 comment in the HelloServiceTest.cs.
All the other staff looks good!

2019-04-18 14:48 UTC, molnarln commented on ASP.NET-Core-Webapp.UnitTests/HelloServiceTests.cs
> +        [Fact]
Please delete this test case.

2019-04-18 15:07 UTC, JohnLackland commented on ASP.NET-Core-Webapp.UnitTests/HelloServiceTests.cs
> +        [Fact]
Done!

2019-04-18 15:07 UTC, molnarln commented on ASP.NET-Core-Webapp.UnitTests/HelloServiceTests.cs
> +        [Fact]
Thanks!

2019-04-22 18:43 UTC, szirmi requested changes
same as PR2 (mock post EP): UnitTestProject1 and packages shouldn't be in repo

2019-04-22 18:43 UTC, szirmi commented on ASP.NET-Core-Webapp.IntegrationTests/Scenarios/MockPostBadgesEndpointTest.cs
> +﻿using ASP.NET_Core_Webapp.Entities;
this file is not part of this PR, remove it

2019-04-22 18:43 UTC, szirmi commented on ASP.NET-Core-Webapp/Controllers/BadgeController.cs
> +            //    return StatusCode(401, new { error = "Unauthorized" });
please always remove unnecessary code

2019-04-23 10:54 UTC, JohnLackland commented on ASP.NET-Core-Webapp/Controllers/BadgeController.cs
> +            //    return StatusCode(401, new { error = "Unauthorized" });
Done!

2019-04-24 08:26 UTC, szirmi approved these changes

2019-04-24 09:29 UTC, merged