Mock get pitches endpoint
green-fox-academy/megalotis-emerald pull request #4
Opened 2019-04-18 14:48 UTC by Balogh08

Please review it, thanks a lot!

2019-04-18 15:18 UTC, osziszab submitted a review, later dismissed

2019-04-22 19:16 UTC, szirmi requested changes

2019-04-22 19:16 UTC, szirmi commented on ASP.NET-Core-Webapp.IntegrationTests/Scenarios/PitchTest.cs
> +            //Assert.Equal(new StringContent(JsonConvert.SerializeObject(new User()), Encoding.UTF8, "application/json"), response.Content.ReadAsStringAsync().Result);
please always remove unnecessary code

2019-04-22 19:16 UTC, szirmi commented on ASP.NET-Core-Webapp/Controllers/PitchController.cs
> +            //user = null;
unnecessary code

2019-04-24 08:26 UTC, szirmi approved these changes

2019-04-24 08:56 UTC, merged